import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios";
import { useEffect, useState } from 'react';
import Card from '../Components/Card';
import PageNav from '../Components/PageNav';

export default function Home() {
	const [characters, setCharacters] = useState([]);
	const [pageInfo, setPageInfo] = useState([]);

	const [characterUrl, setCharacterUrl] = useState("https://rickandmortyapi.com/api/character/?name=Rick");

	var options = {
		method: 'GET',
		url: 'https://rickandmortyapi.com/api/character/?name=Rick',
	};

	useEffect(() => {
		const requestData = async () => {
			const axiosData = await axios.get(characterUrl)
				.then(function (res) {
					setCharacters(res.data.results);
					setPageInfo(res.data.info)
					console.log("Success " + res.data);
				})
				.catch(function (res) {
					if (res instanceof Error) {
						console.log("Failed " + res.message);
					} else {
						console.log("Didn't fail " + res.data);
					}
				});

			//setCharacterUrl(axiosData.data.info.next)
		}
		return requestData();
	}, [characterUrl]);

	let char = characters[0]
	console.log("characters from " + characters);
	console.log("characters from " + char);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<PageNav nav={pageInfo} setCharacterUrl={setCharacterUrl} />
				{/*characters.length > 0 && (
					characters.map((keyName, i) => {
						console.log(`keyName=${keyName} id=${i}`);
						`<div key=${i}>${characters[i].name}</div>`
					}
					//)
				)*/}
				<Card character={characters} />

				<div className={styles.grid}>
					{//characters}
					}
				</div>
			</main>

			<footer className={styles.footer}>

			</footer>
		</div>
	)
}
