import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios";
import { useEffect, useState } from 'react';
import Card from '../Components/Card';

export default function Home() {
	const [characters, setCharacters] = useState([])

	//var axios = require("axios").default;

	var options = {
		method: 'GET',
		url: 'https://rickandmortyapi.com/api/character',
	};

	useEffect(() => {
		/*axios.request(options).then(function (response) {
			console.log(response.data);
			setCharacters(JSON.parse(JSON.stringify(response.data.results)));
		}).catch(function (error) {
			console.error(error);
		});*/
		const requestData = async () => {
			const axiosData = await axios.get("https://rickandmortyapi.com/api/character");
			setCharacters(axiosData.data.results);

		}
		return requestData();
	}, [setCharacters]);

	let char = characters[0]
	console.log("characters from " + characters);
	console.log("characters from " + char);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				{//characters.length > 0 && (
					characters.map((keyName, i) => {
						console.log(`keyName=${keyName} id=${i}`);
						`<div key=${i}>${characters[i].name}</div>`
					}
					//)
				)}
				<Card character={characters} />

				<div className={styles.grid}>
					{//characters}
					}
				</div>
			</main>

			<footer className={styles.footer}>

			</footer>
		</div>
	)
}
